### ISSUE TITLE
LXML Support and XML Validator

### ISSUE THREAD

**Issue by cemakpolat** [tiran/defusedxml#70] opened 2021-07-07 10:00 UTC
Hi developers,

I saw in the defusedxml codes that the lxml will not be supported for the feature releases, do you have a special reason for this? I am asking this due to the lxml XSD validator feature. xmlschema seems the alternative library, however, it is not covered in your tests. How can I combine different library to parse and validate with an XSD schema under defusedxml, if lxml wont be supported anymore.

Thanks for your time!

Best regards
Cem

**Comment by tiran** [comment] 2023-09-28 19:21
Your question is a duplicate of #38 .

**Closed by tiran** 2023-09-28 19:21 UTC
